services:
  db:
    image: postgres:16-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: yellowmetal
      POSTGRES_PASSWORD: yellowmetal
      POSTGRES_DB: yellowmetal
    volumes:
      - yellowmetal-pgdata:/var/lib/postgresql/data

volumes:
  yellowmetal-pgdata:
